name: tmi
description: Dart library for the Twitch Messaging Interface. (Twitch.tv)
version: 0.0.5
homepage: https://github.com/Gazer/tmi.dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  web_socket_client: ^0.1.4
  eventify: ^1.0.1
  logger: ^2.4.0
  http: ^1.2.2

dev_dependencies:
  test:
  mockito: ^5.4.4
  build_runner:
